# Generated by Django 5.1.2 on 2024-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryofservice',
            options={'verbose_name': 'Категория услуги', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='typeofsubservice',
            options={'verbose_name': 'Уточнение услуги', 'verbose_name_plural': 'Уточнение услуг'},
        ),
        migrations.AlterField(
            model_name='categoryofservice',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='typeofservice',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Тип услуги'),
        ),
        migrations.CreateModel(
            name='PeopleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('category_user', models.ManyToManyField(to='stadium.categoryofservice')),
            ],
            options={
                'verbose_name': 'Пользователь категории',
                'verbose_name_plural': 'Пользователи категорий',
            },
        ),
    ]
